FROM mcr.microsoft.com/devcontainers/cpp:ubuntu-22.04
RUN apt-get update && \
    apt-get install -y wget git bash make patch gzip texinfo tar nasm autoconf bison flex libgmp-dev libmpfr-dev libmpc-dev texinfo grub-pc-bin xorriso mtools qemu-system
